### PR TITLE
rfc14/25: add queue to common system attributes list

### PR DESCRIPTION
**Pull request by chu11**
Problem: "queue" is a common system attribute but is not listed.

Add it.

### CODE REVIEW

**Comment by grondo** [comment]
Should `queue` also be added and defined in RFC 14? I didn't see it there and RFC 25 states
> Common system keys are listed below, and their definitions can be found in RFC14.

**Comment by chu11** [comment]
oh good idea

**Comment by chu11** [comment]
added "queue" and a short description in rf14 as well, updating PR title

**Comment by grondo** [comment]
You may have to add
```
urllib3<2
```
to `requirements.txt` to get readthedocs to pass (assuming it is getting the ImportError from urllib3...)

**Comment by chu11** [comment]
woo hoo, that worked

**Review by grondo — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
