### PR TITLE
rfc4: reduce figure width

### LINKED ISSUE #233: rfc4: figures are being rendered too large after RST conversion
I tried this w/ Safari and Chrome on my Mac OSX laptop. Maybe "scale" factors got lost in translation? https://github.com/flux-framework/rfc/blob/master/spec_4.rst

### PR DESCRIPTION
**Pull request by SteVwonder**
Problem: figures intended to be small were taking up the whole screen.  Constrict their size with the `scale` parameter to `figure`.  Also trim extra whitespace from some images so that they are uniform across the RFC.

Closes #233

### CODE REVIEW

**Comment by SteVwonder** [comment]
Thanks @gonsie for the review!  I'm setting the MWP label.

**Comment by SteVwonder** [comment]
@mergifyio rebase

**Comment by SteVwonder** [comment]
Hmmm. Despite the PR-specifc build showing the proper image size: 
Screen Shot 2020-07-20 at 6 00 45 PM

The latest build of master doesn't: 
Screen Shot 2020-07-20 at 6 01 01 PM

The readthedocs backend shows the "latest" tag having been built just minutes ago.  Maybe it is just a caching thing?  Something to loop back to later this week I guess.

**Comment by dongahn** [comment]
Mine's rendering this fine now. Probably caching (would the old shift+mouse-click work)? 

Thanks @gonsie and @SteVwonder!

**Pull request merged**
