### PR TITLE
rfc42: add subprocess protocol RFC

### PR DESCRIPTION
**Pull request by garlick**
Problem: the subprocess execution protocol is not documented.

Add a new RFC.

(Marking as a WIP since I think I need to make another pass double-checking this against code before unleashing it on others)

### CODE REVIEW

**Comment by vsoch** [comment]
oh neat! Is this what I was doing with `flux exec` (and wasn't aware what it was called)?

**Comment by garlick** [comment]
Yep :-)

**Comment by garlick** [comment]
I've made a pass checking this and it seems OK so removing WIP.

**Review by grondo — APPROVED** [review]
LGTM!

**Pull request merged**
