### PR TITLE
spec_14:  Add JSDL reference

### PR DESCRIPTION
**Pull request by lipari**
Came across this reference a while back, but today I thought we should include it as a reference we have seen.

### CODE REVIEW

**Comment by garlick** [comment]
Sorry to let this languish so long!  travis found a spell check error so dictionary needs updating, then it can go in.

**Comment by lipari** [comment]
Is the merging of this PR still waiting for something?

**Comment by garlick** [comment]
Add _Anjomshoaa_ and _JSDL_ to `spell.en.pws` to address the travis failure?

**Comment by lipari** [comment]
Done.

**Pull request merged**
