### PR TITLE
rfc3: update CMB1 protocol after broker refactor

### PR DESCRIPTION
**Pull request by garlick**
* Rename `cmbd` to `flux-broker`
* Reserve `FLUX_NODEID_UPSTREAM`
* Add `FLUX_MSGFLAG_UPSTREAM`

### CODE REVIEW

**Comment by garlick** [comment]
Good point.  Maybe _task_ would be better than _instance_ here?

**Comment by garlick** [comment]
Does that look better?

**Comment by grondo** [comment]
Yeah, I like that better. (It would be nice to have one more person's ACK though) :-)

**Comment by grondo** [comment]
Actually I think this is probably safe to merge and others can comment separately. No reason to leave this update hanging.

**Pull request merged**
