### PR TITLE
rfc31: add clarification on several corner case / use cases

### PR DESCRIPTION
**Pull request by chu11**
This is a proposal for clarifications on #375 and #376.  I'm not sure if this will be liked or not, but could atleast start a discussion.

### CODE REVIEW

**Comment by chu11** [comment]
Hmmm, actually i'm already regretting this:

```
If a constraint object does not list any ``values``, generally speaking
the constraint will always return true and match anything.  The lone exception
to this is the ``not`` operation.  ``{ "not": [] }`` is defined to return false
and match nothing.
```

it should not be for all constraint operations, (note I say "object" above, I meant operation).  Maybe we define this only for `and` and `or`, but everything else is dependent.  i.e. like it can be an error for certain operations.

**Comment by chu11** [comment]
re-pushed with some tweaks, ehhhh?

**Comment by chu11** [comment]
hmmmm, actually should `{ "or": [] }` be false by default?  b/c implementation wise this would be far more common.

```
foreach value in values array:
     if test match == true:
         return true
return false
```

with and being the opposite of course.

```
foreach value in values array:
     if test match == false:
         return false
return true
```

**Comment by grondo** [comment]
Yeah, we shouldn't focus on possible implementations when defining the spec.
This is all a bit of an academic exercise, but if `{ "and": [] }` is true then that implies that empty args is true, which means `{ "or": [] }` should also be true. Perhaps the spec itself is a bit to blame here, maybe empty args shouldn't be allowed to these operations, an empty object is "no constraint" and matches everything, and a constraint that matches nothing isn't specified, but could easily be supplied on a per-case basis with something like `{"name": ["noexist"]}`.

**Review by grondo — APPROVED** [review]
Seems reasonable and a nice clarification.

**Pull request merged**
