### PR TITLE
rfc34: fix test vector

### PR DESCRIPTION
**Pull request by grondo**
Problem: A raw test vector has some commas where semicolons should be.

Fix the typo in the test vector.

### CODE REVIEW

**Review by garlick — APPROVED** [review]
Oh good catch.  Sorry for the error!

**Comment by grondo** [comment]
No problem, the testsuite caught it! I can barely tell the difference between a comma and a semicolon, so I was going cross-eyed looking at that one.

**Comment by vsoch** [comment]
_c++ cackles maniacally from the shadows…_ 👹

**Comment by garlick** [comment]
Maybe we should have defined the delimiter between nodes as a :carrot: or something that stands out!

**Comment by vsoch** [comment]
_bunny rabbit laughs maniacally from the shadows..._ :carrot: :rabbit:

**Pull request merged**
