### PR TITLE
rfc14: Add system.job-name field description

### PR DESCRIPTION
**Pull request by chu11**
My preliminary proposal for a `job-name` field in the jobspec.

### CODE REVIEW

**Comment by grondo** [comment]
In flux-framework/flux-core#2401, I had proposed reserving a dictionary at `attributes.system.job.` for generic job attributes such as `name`. Eventually tools could support display or filtering on any of these attributes.

Reading the edits to the RFC though, a single `job-name` attribute does seem to fit better with some of the existing attributes `cwd`, `environment`, but what do you think about `system.job.name` vs `system.job-name`? It is almost irrelevant at this point, but may allow for easier extending in the future.

**Comment by chu11** [comment]
> what do you think about system.job.name vs system.job-name

My initial feeling was that the "job-name" is sort of a special case, something expected by the system, where as the arbitrary metadata in `system.job` is, well of arbitrary?

Now that I think about it, what would be the difference between having users put metadata in `system.job` vs. `user`?  Isn't `user` where arbitrary user metadata would go?

**Comment by grondo** [comment]
> Now that I think about it, what would be the difference between having users put metadata in system.job vs. user? Isn't user where arbitrary user metadata would go?

I think we said before that `user` is for use by the user and/or application, Flux components wouldn't even look there. The attributes in `system.attributes.job.` may be available for filtering so would probably have to conform to some specification, e.g. may only be of type string, number, or boolean.

**Comment by chu11** [comment]
>  I guess my question more specifically is do you have an objection to job.name vs job-name?

No objection on my part.  I'll re-work.

**Comment by grondo** [comment]
fyi - Some other attributes we might need under `system.job.` that come to mind are `job.bank` `job.wckey`, etc, which might be used by the bank & accounting system.

**Comment by chu11** [comment]
re-worked doing the `system.job.name` approach.

**Comment by chu11** [comment]
> fyi - Some other attributes we might need under system.job. that come to mind are job.bank job.wckey, etc, which might be used by the bank & accounting system.

Ahh, that makes the need far clearer.

**Comment by chu11** [comment]
> Just one nit: the job dictionary probably should be called out as optional, since the section it's in leaves that somewhat ambiguous. Then obviously any keys within it are optional.

Ahhh, I tweaked by changing "The value of the `job` attribute is a dictionary containing additional job metadata. " to "The `job` attribute is an optional dictionary containing job metadata."

**Comment by garlick** [comment]
Thanks!  I'll go ahead and set merge-when-passing since you addressed @grondo's comment earlier.

**Pull request merged**
