### PR TITLE
README.md: add link to RFC 18

### PR DESCRIPTION
**Pull request by garlick**
A link to RFC 18 from the front page is needed.

### CODE REVIEW

**Comment by grondo** [comment]
Thanks. I always forget to update the README.md, so perhaps we could add a simple check to travis along with spellcheck to ensure that any `spec_([0-9]+).adoc` added in a PR also appears in a `link:spec_N` in `README.md`.

**Comment by garlick** [comment]
Good idea!  I'll tack something like that one here.

**Comment by garlick** [comment]
This worked, but for some reason the little green checkmark isn't showing up.  Here's the build with the new `indexcheck` script:

https://travis-ci.org/flux-framework/rfc

**Comment by grondo** [comment]
Thanks and nice work!

**Comment by SteVwonder** [comment]
Thanks!  Sorry I missed that the first time around.  Nice addition to the CI!

**Pull request merged**
